import fakeDataProvider from "ra-data-fakerest";

export const users = [
  {
    id: 1,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Bill",
    day_offs: 90,
  },
  {
    id: 2,
    role: "admin",
    active: true,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Jack",
    day_offs: 20,
  },
  {
    id: 3,
    role: "customer",
    active: false,
    city: "NY",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Samantha",
    day_offs: 30,
  },
  {
    id: 4,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Derek",
    day_offs: 40,
  },
  {
    id: 5,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Rosa",
    day_offs: 50,
  },
  {
    id: 6,
    role: "admin",
    active: false,
    city: "NY",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Amber",
    day_offs: 60,
  },
  {
    id: 7,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "John",
    day_offs: 70,
  },
  {
    id: 11,
    role: "customer",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Bill",
    day_offs: 90,
  },
  {
    id: 12,
    role: "admin",
    active: true,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Jack",
    day_offs: 20,
  },
  {
    id: 13,
    role: "admin",
    active: false,
    city: "NY",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Samantha",
    day_offs: 30,
  },
  {
    id: 14,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Derek",
    day_offs: 40,
  },
  {
    id: 15,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Rosa",
    day_offs: 50,
  },
  {
    id: 16,
    role: "admin",
    active: false,
    city: "NY",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Amber",
    day_offs: 60,
  },
  {
    id: 17,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "John",
    day_offs: 70,
  },
  {
    id: 21,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Bill",
    day_offs: 90,
  },
  {
    id: 22,
    role: "customer",
    active: true,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Jack",
    day_offs: 20,
  },
  {
    id: 23,
    role: "admin",
    active: false,
    city: "NY",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Samantha",
    day_offs: 30,
  },
  {
    id: 24,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Derek",
    day_offs: 40,
  },
  {
    id: 25,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Rosa",
    day_offs: 50,
  },
  {
    id: 26,
    role: "admin",
    active: false,
    city: "NY",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Amber",
    day_offs: 60,
  },
  {
    id: 27,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "John",
    day_offs: 70,
  },
  {
    id: 31,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Bill",
    day_offs: 90,
  },
  {
    id: 32,
    role: "admin",
    active: true,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Jack",
    day_offs: 20,
  },
  {
    id: 33,
    role: "customer",
    active: false,
    city: "NY",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Samantha",
    day_offs: 30,
  },
  {
    id: 34,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Derek",
    day_offs: 40,
  },
  {
    id: 35,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Rosa",
    day_offs: 50,
  },
  {
    id: 36,
    role: "admin",
    active: false,
    city: "NY",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "Amber",
    day_offs: 60,
  },
  {
    id: 37,
    role: "admin",
    active: false,
    city: "Tokyo",
    birthday: "01/08/1991",
    email: "test@gmail.com",
    name: "John",
    day_offs: 70,
  },
];

export const dataProvider = fakeDataProvider({
  users,
});
